### ISSUE TITLE
Einrichten der MongoDB in MongoDBAtlas

### ISSUE THREAD

**Issue by Yejay** [The-Older-Ones/general-project#13]
Lokale MongoDB Instanz für das Deployment unbrauchbar, deshalb muss die Datenbankstruktur auf MongoDBAtlas umgestellt werden, um Cloud Zugriff auf die Daten zu ermöglichen.
Muss mit Backend Team abgesprochen werden, wegen der Umstellung des Datenmodells im Backend.

**Comment by Yejay** [comment]
Anbindung der cloudbasierten Atlas-Version funktioniert so weit. MongoDB Atlas würde jetzt als production database dienen und lokale Instanzen als development. @Deltainu Hat schon rübergeguckt und Admin Rechte gekriegt und wird dieses die nächsten Tage reviewen.

**Comment by Deltainu** [comment]
Hab jetzt alles ausprobiert und funktioniert alles sehr gut.
Den Database Link und den Token key habe ich jetzt in eine .env ausgelagert und der .gitignore hinzugefügt.
Von meiner Seite aus alles tuti.
