### ISSUE TITLE
FRONTEND: Router + Testen

### ISSUE THREAD

**Issue by Veenc0** [The-Older-Ones/general-project#7]
Router testen und probieren, ob Verbindung funktioniert (unterschiedliche Laptops)

**Comment by Deltainu** [comment]
@Yejay @KFDugong @SertanAkpinar  Hab den Router den ich habe ( TP-Link Archer C20 AC750 ) getestet.
Über meinen Tower habe ich das Backend laufen lassen und konnte dann mit meinem Laptop, auf dem das Frontend lief, zugreifen.
Wichtig ist halt nur eine .env oder ähnliches zu machen da man im Frontend die Adresse (IP) angeben muss unter dem das Backend läuft im Netzwerk.

**Comment by Yejay** [comment]
![Image](https://github.com/The-Older-Ones/general-project/assets/28364336/f576ccec-a40c-4fdc-85f5-55c1dee46469)



![Image](https://github.com/The-Older-Ones/general-project/assets/28364336/552516ee-3374-4a03-9040-c35352560ce1)



![Image](https://github.com/The-Older-Ones/general-project/assets/28364336/29b0c6c3-46a5-47a7-a5da-3ad276b460ab)
